website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func

class Note(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    data = db.Column(db.String(10000))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    last_name = db.Column(db.String(150))
    notes = db.relationship('Note')

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'asdfghjkl asdfghjkl'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')
    
    from .models import User, Note

    create_database(app)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app


def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('Created Database!')

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('You have logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Password incorrect please try again', category='error')
        else:
            flash('The email address entered does not exist.', category='error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        last_name = request.form.get('lastName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('This email already Exists! Please log in', category='error')
        elif len(email) < 4:
            flash('Email requires more than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name requires more than 1 character.', category='error')
        elif len(last_name) < 2:
            flash('Last name requires more than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords do not match.', category='error')
        elif len(password1) < 7:
            flash('Password requires a minimum 7 characters.', category='error')
        else:
            new_user = User(email=email, first_name=first_name, last_name=last_name, password=generate_password_hash(password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('You have signed up successfully!', category='success')
            return redirect(url_for('views.home'))
            
    return render_template("sign_up.html", user=current_user)


@auth.route('/shop', methods=['GET', 'POST'])
@login_required
def shop():
    return render_template("ecommerce-products.html", user=current_user)


@auth.route('/article-reviews', methods=['GET', 'POST'])
@login_required
def article_reviews():
    return render_template("article_reviews.html", user=current_user)


@auth.route('/teams', methods=['GET', 'POST'])
@login_required
def teams():
    return render_template("teams.html", user=current_user)


@auth.route('/seminars', methods=['GET', 'POST'])
@login_required
def seminars():
    return render_template("seminars.html", user=current_user)

website/views.py
from flask import render_template, request, flash
from flask import Blueprint, render_template
from flask_login import login_required, current_user

views = Blueprint('views', __name__)

@views.route('/')
@login_required
def home():
    return render_template("home.html", user=current_user)

@views.route('/seminars')
@login_required
def seminars():
    return render_template("seminars.html", user=current_user)

website/templates/article_reviews.html
{% extends "base.html" %} {% block title %}Article Reviews{% endblock %}
{% block content %}
<h1>Article Reviews</h1>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>

    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
        <!-- Fontawesome -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous"/>

        <!-- App css -->
	    <link href="{{ url_for('static', filename='css/app.min.css') }}" rel="stylesheet" type="text/css" id="app-default-stylesheet" />

	    <!-- icons -->
	    <link href="{{ url_for('static', filename='css/icons.min.css') }}" rel="stylesheet" type="text/css" />

        <title>{{ title }}</title>

    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Badminton Centre LC</a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarText">
                    
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{{ url_for('views.home') }}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.teams') }}">Teams</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.article_reviews') }}">Article Reviews</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.seminars') }}">Seminars</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.shop') }}">Shop</a>
                        </li>
                        {% endif %}
                    </ul>
                    

                    <span class="navbar-text">
                        {% if user.is_authenticated %}
                            <a class="nav-item m-2" href="{{ url_for('auth.logout') }}">Logout</a>
                        {% else %}
                            <a class="nav-item m-2" href="{{ url_for('auth.login') }}">Login</a>
                            <a class="nav-item m-2" href="{{ url_for('auth.sign_up') }}">Signup</a>
                        {% endif %}
                    </span>

                </div>
            </div>
        </nav>


        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    {% if category == 'error' %}
                        <div class="alert alert-danger alter-dismissable fade show" role="alert"> 
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% else %}
                        <div class="alert alert-success alter-dismissable fade show" role="alert"> 
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endif %} 
                {% endfor %} 
            {% endif %} 
        {% endwith %}

        <div class="container-fluid m-2 mx-auto">
            {% block content %}{% endblock content %}
        </div>


        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

        <script type="text/javascript" src="{{ url_for('static', filename='js/scripts.js') }}"></script>

    </body>
</html>

website/templates/covid_updates.html
{% extends "base.html" %} {% block title %}Article Reviews{% endblock %}
{% block content %}
<h1>COVID-19 Updates</h1>
{% endblock %}

website/templates/home.html
{% extends "base.html" %}
{% block content %}

    <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">

        <div class="carousel-indicators">
            <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide-1"></button>
            <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide-2"></button>
            <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide-3"></button>
        </div>

        <div class="carousel-inner">

            <div class="carousel-item active">
                <img src="{{ url_for('static', filename='/images/store.jpg') }}" class="d-block w-100">
                <div class="carousel-caption d-none d-md-block">
                    <h1>Coronavirus Update</h1>
                    <p>Following the latest Government Guidelines, Badminton training sessions will resume as normal.</p>
                    <p>Please see your team profile for further updates.</p>
                    <button type="submit" class="btn btn-primary">COVID Updates</button>
                </div>
            </div>

            <div class="carousel-item">
                <img src="{{ url_for('static', filename='/images/store.jpg') }}" class="d-block w-100">
                <div class="carousel-caption d-none d-md-block">
                    <h1>Looking For a Team?</h1>
                    <p>Put your racquets to the test, join one of our teams today
                        and shuttle cock your way to the top of the league.</p>
                    <button type="submit" class="btn btn-primary">Join a Team</button>
                </div>
            </div>

            <div class="carousel-item">
                <img src="{{ url_for('static', filename='/images/store.jpg') }}" class="d-block w-100">
                <div class="carousel-caption d-none d-md-block">
                    <h1>Need some new equipment?</h1>
                    <p>Check out our store to help in your Badminton Career</p>
                    <button type="submit" class="btn btn-primary">Shop Now</button>
                </div>
            </div>

        </div>

        <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>

        <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>

    </div>

{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %}
{% block content %}
<form method="POST">
    <h3 align="center">Login</h3>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input 
            type="email" 
            class="form-control"
            id="email"
            name="email"
            placeholder="Enter email"
        />
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input 
            type="password" 
            class="form-control"
            id="password"
            name="password"
            placeholder="Enter password"
        />
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

website/templates/seminars.html
{% extends "base.html" %} {% block title %}Seminars{% endblock %}
{% block content %}
<h1>Join a Seminar Today!</h1>
{% endblock %}

website/templates/shop.html
{% extends "base.html" %} {% block title %}Shop{% endblock %}
{% block content %}
<h1>e-Store</h1>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %}
{% block content %}
<form method="POST">
    <h3 align="center">Sign Up</h3>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input 
            type="email" 
            class="form-control"
            id="email"
            name="email"
            placeholder="Enter email"
        />
    </div>
    <div class="form-group">
        <label for="firstName">First Name</label>
        <input 
            type="text" 
            class="form-control"
            id="firstName"
            name="firstName"
            placeholder="Enter first name"
        />
    </div>
    <div class="form-group">
        <label for="lastName">Last Name</label>
        <input 
            type="text" 
            class="form-control"
            id="lastName"
            name="lastName"
            placeholder="Enter last name"
        />
    </div>
    <div class="form-group">
        <label for="password1">Password</label>
        <input 
            type="password" 
            class="form-control"
            id="password1"
            name="password1"
            placeholder="Enter password"
        />
    </div>
    <div class="form-group">
        <label for="password2">Re-enter password</label>
        <input 
            type="password" 
            class="form-control"
            id="password2"
            name="password2"
            placeholder="Confirm password"
        />
    </div>    
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

website/templates/teams.html
{% extends "base.html" %} {% block title %}Teams{% endblock %}
{% block content %}
<h1>Check Out Our Teams!</h1>
{% endblock %}